cowork2-elasticsearch:
  container_name: cowork2-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/cowork2/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
cowork2-mysql:
  container_name: cowork2-mysql
  image: mysql:5.7.9
  # volumes:
  #   - ~/volumes/jhipster/cowork2/mysql/:/var/lib/mysql/
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=cowork2
  ports:
    - "3306:3306"
  command: mysqld --lower_case_table_names=1
